name: "Publish @astral-atlas/wildspace-api"

on:
  push:
    tags:
      - '@astral-atlas/wildspace-api@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci -w api --production
      - run: npm run build -w api
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Publish to Github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: wildspace-api.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "test2 - Wildspace API"
          environment_name: main
          version_label: ${{ github.ref_name }}-${{ github.sha }}
          region: ap-southeast-2
          deployment_package: wildspace-api.zip
