name: "Publish @astral-atlas/wildspace-api"

on:
  push:
    tags:
      - '@astral-atlas/wildspace-api@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci -w api --production
      - run: npm run build -w api
      - uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ${{ github.workspace }}
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workspace
      - name: Publish to Github
        uses: softprops/action-gh-release@v1
        with:
          files: wildspace-api.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: api_test
      url: https://api.wildspace.astral-atlas.com
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workspace
      - run: |
          cp -a ./environments/test/. ./
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(cat api/package.json | jq -r .version)"
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "test2 - Wildspace API"
          environment_name: main
          version_label: ${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.sha_short }}
          region: ap-southeast-2
          deployment_package: wildspace-api.zip
