name: Deploy TEST Environment

on:
  push:
    branches:
      - canon

jobs:
  deploy:
    name: "Deploy API"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}

      - run: make artifacts/test-deployment.json