name: "Publish @astral-atlas/wildspace-api"

on:
  push:
    tags:
      - '@astral-atlas/wildspace-www@*'

jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci -w www
      - run: npm run build -w www
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: wildspace-www.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
